teneleven_sandbox_homepage:
    path:  /
    defaults: { _controller: TenelevenSandboxBundle:Default:index }

teneleven_sandbox_dealers:
    path:  /dealers
    defaults: { _controller: teneleven.geolocator.controller:locate, entity: dealer, template: 'TenelevenSandboxBundle:Locator:dealers.html.twig' }

teneleven_sandbox_apartments:
    path:  /apartments
    defaults: { _controller: teneleven.geolocator.controller:locate, entity: apartment, template: 'TenelevenSandboxBundle:Locator:apartments.html.twig' }